# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a0e1e83146d0cbd1bc3a62d1bc4978d8c1376e6467f5524018e28a18fefe3a035b99e10f7d23dbdff1fdf3dc46794be192f33417034292f3a979462dec90ff1

test:
  secret_key_base: e6fb9f1f6cd86e6a094921936dd6731e95f9768f86d19105885e44bbe6ea10b2b609e96db140a40bbf457218b395796438cfcb794a6c8ae68aa65c4b5147ff86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
